#  ETHER-1 Service Node docker template
#  Copyright © 2019 cryon.io
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published
#  by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#  Contact: cryi@tutanota.com

version: "2.4"
services:
  autoheal:
    restart: always
    image: cryi/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - COMPOSE_MODE=true
      - AUTOHEAL_DELAY=60
      - AUTOHEAL_INTERVAL=5
      - STOP_TIMEOUT=120

  ip-map:
    restart: always
    init: true
    build: ./containers/ip-map
    stop_grace_period: 2m
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:       
      - "./.icc/map-ip:/map-ip:ro"
      - "./.icc/mapped-ip:/mapped-ip:rw"

  mn:
    restart: always
    init: true
    build: ./containers/etho
    stop_grace_period: 2m
    volumes:
      - "./data:/home/etho/.ether1:rw"
      - "./.icc/map-ip:/map-ip:rw"
      - "./.icc/mapped-ip:/mapped-ip:ro"
    pids_limit: 100
    labels:
      - autoheal=true
    ports:
      - "30305:30305"
    env_file:
      - "./.env"
#    security_opt:
#      - apparmor=ETHO-armor